### ISSUE TITLE
It says usage too few arguments

### ISSUE THREAD

**Issue by ghost** [dalelyunas/manga-translator#2]
Hi im new python user and i wanna use your program but its says
 usage: manga_translate.py [-h] img out
manga_translate.py: error: too few arguments

**Comment by edvinkuric** [comment]
Hey @cartals , welcome to python
what command did you type in python exactly?
Did you specify the output-folder?
What Version of python did you use when trying it out?

**Comment by triplewy** [comment]
I get this error:
<pre><code>alexs-macbook:manga-translator alexyu$ python manga_translate.py ./img/ekiben-1.jpg ./result
Traceback (most recent call last):
  File "manga_translate.py", line 30, in <module>
    main()
  File "manga_translate.py", line 19, in main
    blurbs = locate_bubbles.get_blurbs(img)
  File "/Users/alexyu/pythonProjects/manga-translator/locate_bubbles.py", line 46, in get_blurbs
    im2, contours, hierarchy = cv2.findContours(img_gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack</code> </pre>

**Comment by fieldhouse** [comment]
I get the same error.  brew install of Python 2.7.16 on a mac.
Basic steps I ran through to get things set up are:
brew install tesseract
brew install tesseract-lang
brew install opencv
installed node
npm install --save google-translate-api
pip install pytesseract
first run I got  No module named dill so
 pip install dill

That last line of the readme has me worried... 
NumPy, SciPy, some other Python packages.  Are there other dependencies that we need to install?

**Comment by ghost** [comment]
@fieldhouse i was able to run it but it is glitchy af, it is unusable.

**Comment by Banhammer151** [comment]
For those having issues make sure you are using opencv 3.x and not 2.x

a. Packages for standard desktop environments (Windows, macOS, almost any GNU/Linux distribution)
run pip install opencv-python if you need only main modules
run pip install opencv-contrib-python if you need both main and contrib modules (check extra modules listing from OpenCV documentation)
